-- MySQL Script generated by MySQL Workbench
-- Mon Feb  7 17:00:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema ferreteria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ferreteria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ferreteria` DEFAULT CHARACTER SET utf8mb4 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clasificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clasificacion` (
  `idclase` INT NOT NULL,
  `nombre` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`idclase`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idProducto` BIGINT(5) NOT NULL AUTO_INCREMENT,
  `nobre` VARCHAR(45) NOT NULL,
  `stock` SMALLINT(5) NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `clase` ENUM('General,Sanitario,Tornilleria,Mineria,Agreicultura,Construccion,materailes electricos, equipos y herramientas, tuberia y pvc, lubricantes, dotaciones') NOT NULL,
  `claseId` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_clase1_idx` (`claseId` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_clase1`
    FOREIGN KEY (`claseId`)
    REFERENCES `mydb`.`clasificacion` (`idclase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `idPersona` VARCHAR(45) NOT NULL,
  `tipodocumento` ENUM('Cedula', 'Nit') NULL,
  `documento` VARCHAR(45) NULL,
  `correo` VARCHAR(75) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `telefono` VARCHAR(75) NULL,
  `password` VARCHAR(45) NULL,
  `rol` ENUM('administrador', 'vendedor', 'cliente', 'Proveedor Natural', 'Proveedor Juridico') NULL,
  `estado` ENUM('activo', 'inactivo') NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marca` (
  `idMarca` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medida` (
  `idMedida` INT NOT NULL AUTO_INCREMENT,
  `medida` SMALLINT(3) NOT NULL,
  `tipoMedida` ENUM('metrico', 'masa', 'volumen', 'longitud') NOT NULL,
  `unidadMedida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMedida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`material` (
  `idMaterial` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMaterial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `idProveedor_Juridicocol` INT NOT NULL,
  `Nit` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(65) NOT NULL,
  `direccion` VARCHAR(75) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `rol` ENUM('proveedor_natural', 'Proveedor_Juridico') NOT NULL,
  PRIMARY KEY (`idProveedor_Juridicocol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venta` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `PersonaId` VARCHAR(45) NOT NULL,
  `monto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_Factura_Persona1_idx` (`PersonaId` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Persona1`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto_has_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto_has_factura` (
  `Producto_codigo` BIGINT(5) NOT NULL,
  `factura_codigo` INT NOT NULL,
  PRIMARY KEY (`Producto_codigo`, `factura_codigo`),
  INDEX `fk_Producto_has_factura_factura1_idx` (`factura_codigo` ASC) VISIBLE,
  INDEX `fk_Producto_has_factura_Producto1_idx` (`Producto_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_has_factura_Producto1`
    FOREIGN KEY (`Producto_codigo`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_factura_factura1`
    FOREIGN KEY (`factura_codigo`)
    REFERENCES `mydb`.`venta` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto_has_factura_has_Producto_has_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto_has_factura_has_Producto_has_factura` (
  `Producto_has_factura_Producto_codigo` BIGINT(5) NOT NULL,
  `Producto_has_factura_factura_codigo` INT NOT NULL,
  `Producto_has_factura_Producto_codigo1` BIGINT(5) NOT NULL,
  `Producto_has_factura_factura_codigo1` INT NOT NULL,
  PRIMARY KEY (`Producto_has_factura_Producto_codigo`, `Producto_has_factura_factura_codigo`, `Producto_has_factura_Producto_codigo1`, `Producto_has_factura_factura_codigo1`),
  INDEX `fk_Producto_has_factura_has_Producto_has_factura_Producto_h_idx` (`Producto_has_factura_Producto_codigo1` ASC, `Producto_has_factura_factura_codigo1` ASC) VISIBLE,
  INDEX `fk_Producto_has_factura_has_Producto_has_factura_Producto_h_idx1` (`Producto_has_factura_Producto_codigo` ASC, `Producto_has_factura_factura_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_has_factura_has_Producto_has_factura_Producto_has1`
    FOREIGN KEY (`Producto_has_factura_Producto_codigo` , `Producto_has_factura_factura_codigo`)
    REFERENCES `mydb`.`Producto_has_factura` (`Producto_codigo` , `factura_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_factura_has_Producto_has_factura_Producto_has2`
    FOREIGN KEY (`Producto_has_factura_Producto_codigo1` , `Producto_has_factura_factura_codigo1`)
    REFERENCES `mydb`.`Producto_has_factura` (`Producto_codigo` , `factura_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Detalle_Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Detalle_Compra` (
  `idDetallecompra` VARCHAR(45) NOT NULL,
  `cantidad` DOUBLE NOT NULL,
  `valorTotal` DOUBLE NOT NULL,
  `Producto_idProducto` BIGINT(5) NOT NULL,
  `Compra_idFactura` INT NOT NULL,
  INDEX `fk_Detalle_Compra_Producto2_idx` (`Producto_idProducto` ASC) VISIBLE,
  INDEX `fk_Detalle_Compra_Compra1_idx` (`Compra_idFactura` ASC) VISIBLE,
  PRIMARY KEY (`idDetallecompra`),
  CONSTRAINT `fk_Detalle_Compra_Producto2`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Compra_Compra1`
    FOREIGN KEY (`Compra_idFactura`)
    REFERENCES `mydb`.`Compra` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Detalle_Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Detalle_Venta` (
  `idDetalle_Compracol` VARCHAR(45) NOT NULL,
  `cantidad` DOUBLE NOT NULL,
  `valor_Total` DOUBLE NOT NULL,
  `ProductoId` BIGINT(5) NOT NULL,
  `ventaId` INT NOT NULL,
  `MedidaId` INT NOT NULL,
  PRIMARY KEY (`idDetalle_Compracol`),
  INDEX `fk_Detalle_Compra_Producto1_idx` (`ProductoId` ASC) VISIBLE,
  INDEX `fk_Detalle_Compra_Factura1_idx` (`ventaId` ASC) VISIBLE,
  INDEX `fk_Detalle_Compra_Medida1_idx` (`MedidaId` ASC) VISIBLE,
  CONSTRAINT `fk_Detalle_Compra_Producto1`
    FOREIGN KEY (`ProductoId`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Compra_Factura1`
    FOREIGN KEY (`ventaId`)
    REFERENCES `mydb`.`venta` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Compra_Medida1`
    FOREIGN KEY (`MedidaId`)
    REFERENCES `mydb`.`medida` (`idMedida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Detalle_Compra_has_Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Detalle_Compra_has_Material` (
  `Detalle_Compra_idDetalle_Compracol` VARCHAR(45) NOT NULL,
  `Material_idMaterial` INT NOT NULL,
  PRIMARY KEY (`Detalle_Compra_idDetalle_Compracol`, `Material_idMaterial`),
  INDEX `fk_Detalle_Compra_has_Material_Material1_idx` (`Material_idMaterial` ASC) VISIBLE,
  INDEX `fk_Detalle_Compra_has_Material_Detalle_Compra1_idx` (`Detalle_Compra_idDetalle_Compracol` ASC) VISIBLE,
  CONSTRAINT `fk_Detalle_Compra_has_Material_Detalle_Compra1`
    FOREIGN KEY (`Detalle_Compra_idDetalle_Compracol`)
    REFERENCES `mydb`.`Detalle_Venta` (`idDetalle_Compracol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Compra_has_Material_Material1`
    FOREIGN KEY (`Material_idMaterial`)
    REFERENCES `mydb`.`material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productoMaterial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productoMaterial` (
  `idProductoMaterialcol` INT NOT NULL,
  `Producto_idProducto` BIGINT(5) NOT NULL,
  `Material_idMaterial` INT NOT NULL,
  PRIMARY KEY (`idProductoMaterialcol`, `Producto_idProducto`, `Material_idMaterial`),
  INDEX `fk_Producto_has_Material_Material1_idx` (`Material_idMaterial` ASC) VISIBLE,
  INDEX `fk_Producto_has_Material_Producto1_idx` (`Producto_idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_has_Material_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Material_Material1`
    FOREIGN KEY (`Material_idMaterial`)
    REFERENCES `mydb`.`material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compra` (
  `idFactura` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `monto` VARCHAR(45) NOT NULL,
  `PersonaId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_Compra_Persona1_idx` (`PersonaId` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_Persona1`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Detalle_Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Detalle_Compra` (
  `idDetallecompra` VARCHAR(45) NOT NULL,
  `cantidad` DOUBLE NOT NULL,
  `valorTotal` DOUBLE NOT NULL,
  `Producto_idProducto` BIGINT(5) NOT NULL,
  `Compra_idFactura` INT NOT NULL,
  INDEX `fk_Detalle_Compra_Producto2_idx` (`Producto_idProducto` ASC) VISIBLE,
  INDEX `fk_Detalle_Compra_Compra1_idx` (`Compra_idFactura` ASC) VISIBLE,
  PRIMARY KEY (`idDetallecompra`),
  CONSTRAINT `fk_Detalle_Compra_Producto2`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Compra_Compra1`
    FOREIGN KEY (`Compra_idFactura`)
    REFERENCES `mydb`.`Compra` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Marca_has_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Marca_has_Producto` (
  `Marca_idCodigo` INT NOT NULL,
  `Producto_idProducto` BIGINT(5) NOT NULL,
  PRIMARY KEY (`Marca_idCodigo`, `Producto_idProducto`),
  INDEX `fk_Marca_has_Producto_Producto1_idx` (`Producto_idProducto` ASC) VISIBLE,
  INDEX `fk_Marca_has_Producto_Marca1_idx` (`Marca_idCodigo` ASC) VISIBLE,
  CONSTRAINT `fk_Marca_has_Producto_Marca1`
    FOREIGN KEY (`Marca_idCodigo`)
    REFERENCES `mydb`.`marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Marca_has_Producto_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Logueo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Logueo` (
  `idLogueo` INT NOT NULL,
  `documento` INT NOT NULL,
  `contraseña` VARCHAR(65) NOT NULL,
  `rol` ENUM('administrador', 'vendedor') NULL,
  `PersonaId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLogueo`),
  INDEX `fk_Logueo_Persona1_idx` (`PersonaId` ASC) VISIBLE,
  CONSTRAINT `fk_Logueo_Persona1`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productoMedida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productoMedida` (
  `idProductoMedidacol` INT NOT NULL,
  `Producto_idProducto` BIGINT(5) NOT NULL,
  `Medida_codigo` INT NOT NULL,
  PRIMARY KEY (`idProductoMedidacol`, `Producto_idProducto`, `Medida_codigo`),
  INDEX `fk_Producto_has_Medida_Medida1_idx` (`Medida_codigo` ASC) VISIBLE,
  INDEX `fk_Producto_has_Medida_Producto1_idx` (`Producto_idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_has_Medida_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Medida_Medida1`
    FOREIGN KEY (`Medida_codigo`)
    REFERENCES `mydb`.`medida` (`idMedida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marcaProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marcaProducto` (
  `idMarcaProductocol` INT NOT NULL,
  `Marca_idCodigo` INT NOT NULL,
  `Producto_idProducto` BIGINT(5) NOT NULL,
  PRIMARY KEY (`idMarcaProductocol`, `Marca_idCodigo`, `Producto_idProducto`),
  INDEX `fk_Marca_has_Producto1_Producto1_idx` (`Producto_idProducto` ASC) VISIBLE,
  INDEX `fk_Marca_has_Producto1_Marca1_idx` (`Marca_idCodigo` ASC) VISIBLE,
  CONSTRAINT `fk_Marca_has_Producto1_Marca1`
    FOREIGN KEY (`Marca_idCodigo`)
    REFERENCES `mydb`.`marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Marca_has_Producto1_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `ferreteria` ;

-- -----------------------------------------------------
-- Table `ferreteria`.`clasificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ferreteria`.`clasificacion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ferreteria`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ferreteria`.`persona` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipodocumento` ENUM('Cedula', 'Nit') NULL DEFAULT NULL,
  `documento` INT(11) NULL DEFAULT NULL,
  `correo` VARCHAR(75) NULL DEFAULT NULL,
  `nombre` VARCHAR(75) NULL DEFAULT NULL,
  `apellido` VARCHAR(75) NULL DEFAULT NULL,
  `telefono` VARCHAR(75) NULL DEFAULT NULL,
  `contrasena` VARCHAR(75) NULL DEFAULT NULL,
  `rol` ENUM('administrador', 'empleado', 'cliente', 'proveedorjuridico', 'proveedor_natural') NULL DEFAULT NULL,
  `estado` ENUM('activo', 'inactivo') NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ferreteria`.`facturacompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ferreteria`.`facturacompra` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `monto` VARCHAR(75) NOT NULL,
  `proveedor_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_compra_persona1_idx` (`proveedor_id` ASC) VISIBLE,
  CONSTRAINT `fk_compra_persona1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `ferreteria`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ferreteria`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ferreteria`.`producto` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NOT NULL,
  `stock` SMALLINT(6) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `clasificacion_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_producto_clasificacion1_idx` (`clasificacion_id` ASC) VISIBLE,
  CONSTRAINT `fk_producto_clasificacion1`
    FOREIGN KEY (`clasificacion_id`)
    REFERENCES `ferreteria`.`clasificacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ferreteria`.`detallecompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ferreteria`.`detallecompra` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cantidad` DOUBLE NOT NULL,
  `valor` DOUBLE NOT NULL,
  `compra_id` INT(11) NOT NULL,
  `producto_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detallecompra_compra1_idx` (`compra_id` ASC) VISIBLE,
  INDEX `fk_detallecompra_producto1_idx` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `fk_detallecompra_compra1`
    FOREIGN KEY (`compra_id`)
    REFERENCES `ferreteria`.`facturacompra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detallecompra_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `ferreteria`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ferreteria`.`facturaventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ferreteria`.`facturaventa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `monto` VARCHAR(75) NOT NULL,
  `cliente_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_facturaventa_persona1_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_facturaventa_persona1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `ferreteria`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ferreteria`.`medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ferreteria`.`medida` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NOT NULL,
  `tipoMedida` ENUM('metrico', 'masa', 'volumen', 'longitud') NOT NULL,
  `unidadMedida` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ferreteria`.`detalleventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ferreteria`.`detalleventa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cantidad` DOUBLE NOT NULL,
  `valor` DOUBLE NOT NULL,
  `facturaventa_id` INT(11) NOT NULL,
  `medida_id` INT(11) NOT NULL,
  `producto_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalleventa_facturaventa1_idx` (`facturaventa_id` ASC) VISIBLE,
  INDEX `fk_detalleventa_medida1_idx` (`medida_id` ASC) VISIBLE,
  INDEX `fk_detalleventa_producto1_idx` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `fk_detalleventa_facturaventa1`
    FOREIGN KEY (`facturaventa_id`)
    REFERENCES `ferreteria`.`facturaventa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleventa_medida1`
    FOREIGN KEY (`medida_id`)
    REFERENCES `ferreteria`.`medida` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleventa_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `ferreteria`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ferreteria`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ferreteria`.`marca` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ferreteria`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ferreteria`.`material` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ferreteria`.`producto_Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ferreteria`.`producto_Marca` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `producto_id` BIGINT(20) NOT NULL,
  `marca_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_producto_Marca_producto1_idx` (`producto_id` ASC) VISIBLE,
  INDEX `fk_producto_Marca_marca1_idx` (`marca_id` ASC) VISIBLE,
  CONSTRAINT `fk_producto_Marca_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `ferreteria`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_Marca_marca1`
    FOREIGN KEY (`marca_id`)
    REFERENCES `ferreteria`.`marca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ferreteria`.`producto_Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ferreteria`.`producto_Material` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `producto_id` BIGINT(20) NOT NULL,
  `material_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_producto_Material_producto1_idx` (`producto_id` ASC) VISIBLE,
  INDEX `fk_producto_Material_material1_idx` (`material_id` ASC) VISIBLE,
  CONSTRAINT `fk_producto_Material_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `ferreteria`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_Material_material1`
    FOREIGN KEY (`material_id`)
    REFERENCES `ferreteria`.`material` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ferreteria`.`producto_Medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ferreteria`.`producto_Medida` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `producto_id` BIGINT(20) NOT NULL,
  `medida_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_producto_Medida_producto1_idx` (`producto_id` ASC) VISIBLE,
  INDEX `fk_producto_Medida_medida1_idx` (`medida_id` ASC) VISIBLE,
  CONSTRAINT `fk_producto_Medida_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `ferreteria`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_Medida_medida1`
    FOREIGN KEY (`medida_id`)
    REFERENCES `ferreteria`.`medida` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ferreteria`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ferreteria`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ferreteria`.`table2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ferreteria`.`table2` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
