<?php

namespace App\Models;

use JetBrains\PhpStorm\Internal\TentativeType;
use App\Interfaces\Model;
use Carbon\Carbon;
use Exception;
use JsonSerializable;
class facturacompra extends AbstractDBConnection implements \App\Interfaces\Model
{

    private ?int $id;
    private carbon $fecha;
    private string $monto;
    private int $proveedor_id;

    //relaciones
    private ?array $DetalleCompraFacturaCompra;
    Private Persona $Persona;

    /**
     * @param int|null $id
     * @param Carbon $fecha
     * @param string $monto
     * @param int $proveedor_id
     */
    public function __construct(array $FacturaCompra=[])
    {
        parent::__construct();
       $this->setId ($FacturaCompra['id'] ?? NULL);
       $this->setFecha(!empty($FacturaCompra['fecha'])?
           carbon::parse($FacturaCompra['fecha']) : new carbon());
       $this->setMonto ($FacturaCompra ['monto'] ?? '');
       $this ->setProveedorId($FacturaCompra ['proveedor_id'] ?? 0);
    }

    public function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @param int|null $id
     */
    public function setId(?int $id): void
    {
        $this->id = $id;
    }

    /**
     * @return Carbon
     */
    public function getFecha(): Carbon
    {
        return $this->fecha;
    }

    /**
     * @param Carbon $fecha
     */
    public function setFecha(Carbon $fecha): void
    {
        $this->fecha = $fecha;
    }

    /**
     * @return string
     */
    public function getMonto(): string
    {
        return $this->monto;
    }

    /**
     * @param string $monto
     */
    public function setMonto(string $monto): void
    {
        $this->monto = $monto;
    }

    /**
     * @return int
     */
    public function getProveedorId(): int
    {
        return $this->proveedor_id;
    }

    /**
     * @param int $proveedor_id
     */
    public function setProveedorId(int $proveedor_id): void
    {
        $this->proveedor_id = $proveedor_id;
    }

    /**
     * @return array|null
     */
    public function getDetalleCompraFacturaCompra(): ?array
    {
        return $this->DetalleCompraFacturaCompra;
    }

    /**
     * @param array|null $DetalleCompraFacturaCompra
     */
    public function setDetalleCompraFacturaCompra(?array $DetalleCompraFacturaCompra): void
    {
        $this->DetalleCompraFacturaCompra = $DetalleCompraFacturaCompra;
    }

    /**
     * @return Persona
     */
    public function getPersona(): Persona
    {
        return $this->Persona;
    }

    /**
     * @param Persona $Persona
     */
    public function setPersona(Persona $Persona): void
    {
        $this->Persona = $Persona;
    }




    protected function save(string $query): ?bool
    {
        // TODO: Implement save() method.
    }

    function insert(): ?bool
    {
        // TODO: Implement insert() method.
    }

    function update(): ?bool
    {
        // TODO: Implement update() method.
    }

    function deleted(): ?bool
    {
        // TODO: Implement deleted() method.
    }

    static function search($query): ?array
    {
        // TODO: Implement search() method.
    }

    static function searchForId(int $id): ?object
    {
        // TODO: Implement searchForId() method.
    }

    static function getAll(): ?array
    {
        // TODO: Implement getAll() method.
    }

    /**
     * @inheritDoc
     */
    public function jsonSerialize(): mixed
    {
        // TODO: Implement jsonSerialize() method.
    }
}